<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'controllerinterface' => '/ControllerInterface.php',
                'requestinterface' => '/RequestInterface.php',
                'responseinterface' => '/ResponseInterface.php',
                'shoppingcart' => '/ShoppingCart.php',
                'shoppingcartcontroller' => '/ShoppingCartController.php',
                'shoppingcartcontrollertest' => '/ShoppingCartControllerTest.php',
                'shoppingcartiteminterface' => '/ShoppingCartItemInterface.php',
                'shoppingcartrepositoryinterface' => '/ShoppingCartRepositoryInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
