<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'computingcoursetest' => '/ComputingCourseTest.php',
                'coursefactorytest' => '/CourseFactoryTest.php',
                'coursetest' => '/CourseTest.php',
                'idtest' => '/IdTest.php',
                'latincoursetest' => '/LatinCourseTest.php',
                'lawcoursetest' => '/LawCourseTest.php',
                'lecturertest' => '/LecturerTest.php',
                'mathematicscoursetest' => '/MathematicsCourseTest.php',
                'physicscoursetest' => '/PhysicsCourseTest.php',
                'psychologycoursetest' => '/PsychologyCourseTest.php',
                'semester201701test' => '/Semester201701Test.php',
                'semester201702test' => '/Semester201702Test.php',
                'semesterbuildertest' => '/SemesterBuilderTest.php',
                'semestertest' => '/SemesterTest.php',
                'staffidtest' => '/StaffIdTest.php',
                'studenttest' => '/StudentTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
