<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'email' => '/ValueObjects/Email.php',
                'pdofactory' => '/Classes/PDOFactory.php',
                'suxxcommentcontroller' => '/Controllers/commentController.php',
                'suxxcontroller' => '/Controllers/controller.php',
                'suxxdatabase' => '/Classes/database.php',
                'suxxdatabaseresult' => '/Classes/DatabaseResult.php',
                'suxxerrorcontroller' => '/Controllers/errorController.php',
                'suxxerrorview' => '/Views/errorview.php',
                'suxxfactory' => '/Classes/factory.php',
                'suxxhomecontroller' => '/Controllers/homeController.php',
                'suxxlogincontroller' => '/Controllers/loginController.php',
                'suxxproductcontroller' => '/Controllers/productController.php',
                'suxxproducttabledatagateway' => '/Gateways/ProductTableDataGateway.php',
                'suxxregistercontroller' => '/Controllers/registerController.php',
                'suxxregistrationformcommand' => '/Classes/RegistrationFormCommand.php',
                'suxxregistrator' => '/Classes/Registrator.php',
                'suxxrequest' => '/Classes/request.php',
                'suxxresponse' => '/Classes/response.php',
                'suxxresponseexception' => '/Exceptions/ResponseException.php',
                'suxxrouter' => '/Classes/Router.php',
                'suxxstaticview' => '/Views/staticview.php',
                'suxxusertabledatagateway' => '/Gateways/UserTableDataGateway.php',
                'suxxviewinterface' => '/Views/viewinterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
