<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'burgerbuildertest' => '/BurgerBuilderTest.php',
                'burgerconsolerenderertest' => '/BurgerConsoleRendererTest.php',
                'burgertest' => '/BurgerTest.php',
                'cheeseburgerrecipetest' => '/CheeseburgerRecipeTest.php',
                'cheesetest' => '/CheeseTest.php',
                'hamburgerrecipetest' => '/HamburgerRecipeTest.php',
                'ingredientfactorytest' => '/IngredientFactoryTest.php',
                'ingredientnamecollectiontest' => '/IngredientNameCollectionTest.php',
                'ingredientrepositorytest' => '/IngredientRepositoryTest.php',
                'lowerbreadtest' => '/LowerBreadTest.php',
                'pattytest' => '/PattyTest.php',
                'pricetest' => '/PriceTest.php',
                'saladtest' => '/SaladTest.php',
                'saucetest' => '/SauceTest.php',
                'tomatotest' => '/TomatoTest.php',
                'upperbreadtest' => '/UpperBreadTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
