<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'author' => '/f_Author.php',
                'blog' => '/f_Blog.php',
                'post' => '/f_Post.php',
                'comment' => '/f_Comment.php',
                'blogexception' => '/BlogException.php',
                'permissionnotfoundexception' => '/PermissionNotFoundException.php',
                'removepermissionexception' => '/RemovePermissionException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
