<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'gettext\\exceptions\\gettextfileexception' => '/Exceptions/GetTextFileException.php',
                'gettext\\poparser' => '/PoParser.php',
                'gettext\\v2\\gettextentry' => '/V2/GetTextEntry.php',
                'gettext\\v2\\poparser' => '/V2/PoParser.php',
                'gettext\\v2\\poprocessor' => '/V2/PoProcessor.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
