<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'gettext\\exceptions\\gettextfileexception' => '/Exceptions/GetTextFileException.php',
                'gettext\\gettextentry' => '/GetTextEntry.php',
                'gettext\\mysqltopoexporter' => '/MySqlToPoExporter.php',
                'gettext\\pdofactory' => '/PDOFactory.php',
                'gettext\\poparser' => '/PoParser.php',
                'gettext\\potomysqlimporter' => '/PoToMySqlImporter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
