<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'application' => '/application/Application.php',
                'auction' => '/domain/Auction.php',
                'auctionmapper' => '/application/AuctionMapper.php',
                'bid' => '/domain/Bid.php',
                'bidbelowinitialpriceexception' => '/domain/BidBelowInitialPriceException.php',
                'bidcommand' => '/application/BidCommand.php',
                'bidrouter' => '/application/BidRouter.php',
                'bidtoolowexception' => '/domain/BidTooLowException.php',
                'command' => '/application/Command.php',
                'duplicateemailexception' => '/domain/DuplicateEmailException.php',
                'email' => '/domain/Email.php',
                'emptynicknameexception' => '/domain/EmptyNicknameException.php',
                'enddatebeforestartdateexception' => '/domain/EndDateBeforeStartDateException.php',
                'eur' => '/domain/EUR.php',
                'factory' => '/application/Factory.php',
                'getrequest' => '/application/GetRequest.php',
                'getrequestrouter' => '/application/GetRequestRouter.php',
                'getrequestrouterchain' => '/application/GetRequestRouterChain.php',
                'illegalbidderexception' => '/domain/IllegalBidderException.php',
                'invalidemailexception' => '/domain/InvalidEmailException.php',
                'nickname' => '/domain/Nickname.php',
                'page' => '/application/Page.php',
                'postrequest' => '/application/PostRequest.php',
                'postrequestrouter' => '/application/PostRequestRouter.php',
                'postrequestrouterchain' => '/application/PostRequestRouterChain.php',
                'query' => '/application/Query.php',
                'redirect' => '/application/Redirect.php',
                'request' => '/application/Request.php',
                'response' => '/application/Response.php',
                'session' => '/application/Session.php',
                'user' => '/domain/User.php',
                'userrepository' => '/domain/UserRepository.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
