<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'burger' => '/src/Burger.php',
                'burgerfactory' => '/src/BurgerFactory.php',
                'cheese' => '/src/Cheese.php',
                'cheeseburgerrecipe' => '/src/CheeseburgerRecipe.php',
                'hamburgerrecipe' => '/src/HamburgerRecipe.php',
                'ingredient' => '/src/Ingredient.php',
                'patty' => '/src/Patty.php',
                'recipe' => '/src/Recipe.php',
                'salad' => '/src/Salad.php',
                'sauce' => '/src/Sauce.php',
                'tomato' => '/src/Tomato.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
