<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'abstractsemester' => '/AbstractSemester.php',
                'computingcourse' => '/ComputingCourse.php',
                'course' => '/Course.php',
                'id' => '/Id.php',
                'latincourse' => '/LatinCourse.php',
                'lawcourse' => '/LawCourse.php',
                'lecturer' => '/Lecturer.php',
                'mathematicscourse' => '/MathematicsCourse.php',
                'physicscourse' => '/PhysicsCourse.php',
                'psychologycourse' => '/PsychologyCourse.php',
                'semester' => '/Semester.php',
                'semester201701' => '/Semester201701.php',
                'semester201702' => '/Semester201702.php',
                'staffid' => '/StaffId.php',
                'student' => '/Student.php',
                'uuid' => '/UUID.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
